/**
 * Gamle WordPress-vedleggssider (attachment pages), generert fra WXR-eksporten 28.09.2026.
 * Dette er HTML-sidene WordPress laget for hvert bilde, ikke selve bildefilene under /wp-content/uploads/.
 * Regler og begrunnelse: docs/migration/wordpress-archives-and-media.md.
 *
 * Vedlegg der parent-artikkelen er en 410-kandidat (23) eller er utsatt (5),
 * står ikke her. De følger parent-artikkelens beslutning og gir 404 til den er tatt.
 */

/** Vedlegg med publisert parent: 301 direkte til parent-artikkelens endelige URL. */
export const attachmentRedirects: { from: string; to: string }[] = [
  { from: "/affiliate-markedsforing-i-norge-er-det-enklere/jobber_pa_cafe_affiliate/", to: "/affiliate-markedsforing-i-norge-er-det-enklere/" },
  { from: "/affiliate-markedsforing-i-norge-er-det-enklere/norsk_affiliate_markedsforing/", to: "/affiliate-markedsforing-i-norge-er-det-enklere/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/amazon_affiliateprogram_logo/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/amazon_affiliateprogram/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/amazon_salg_og_klikk_og_rater/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/december_sales_2015/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/excel_amazon_provisjon/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/julehandel_amazon_com/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/amazon-julehandel-over-alle-stovelskaft/julehandel_amazon/", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  { from: "/de-beste-norske-seo-bloggene/billig_seo/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/blackcapseo-logo-for-blogg-300x300/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/fredrik_blanke_200/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/hanspetter-info_logo/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/inboundbloggen_logo/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/netlife_blogg/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/norske_seo_blogger_feature/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/norske_seo_blogger_featured/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/print/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/red_performance_logo/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/synlighetsbloggen_logo/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/trond-lyngbo-head-of-seo-at-mediacom-norge-seo-columnist-at-search-engine-land/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/wpskolen_blogg/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/de-beste-norske-seo-bloggene/wpskolen_logo/", to: "/de-beste-norske-seo-bloggene/" },
  { from: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/amazon_affiliate_program_kjore/", to: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/" },
  { from: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/prosentskjema_amazon_2020/", to: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/" },
  { from: "/er-det-umulig-a-tjene-penger-pa-nett/er_det_umulig_a_tjene_penger_pa_nett/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/er-det-umulig-a-tjene-penger-pa-nett/excel_income_sheet_400/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/er-det-umulig-a-tjene-penger-pa-nett/min_egen_sjef_kolsastoppen/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/er-det-umulig-a-tjene-penger-pa-nett/sporsmalstegn/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/gode-verktoy-for-sokeordsanalyse/jaaxy_keyword_tool/", to: "/gode-verktoy-for-sokeordsanalyse/" },
  { from: "/gode-verktoy-for-sokeordsanalyse/kwfinder_norsk_2/", to: "/gode-verktoy-for-sokeordsanalyse/" },
  { from: "/gode-verktoy-for-sokeordsanalyse/kwfinder_norsk/", to: "/gode-verktoy-for-sokeordsanalyse/" },
  { from: "/gode-verktoy-for-sokeordsanalyse/sokeordsanalyse_pa_norsk/", to: "/gode-verktoy-for-sokeordsanalyse/" },
  { from: "/gode-verktoy-for-sokeordsanalyse/video-thumbnail-keyword-tool-pro-case-study-c3-prague/", to: "/gode-verktoy-for-sokeordsanalyse/" },
  { from: "/gratis-bilder/depositphotos_bilder/", to: "/gratis-bilder/" },
  { from: "/gratis-bilder/gratis_bilder/", to: "/gratis-bilder/" },
  { from: "/gratis-bilder/pexels_bilder/", to: "/gratis-bilder/" },
  { from: "/gratis-bilder/pixabay_bilder/", to: "/gratis-bilder/" },
  { from: "/gratis-bilder/unsplash_norge/", to: "/gratis-bilder/" },
  { from: "/har-jeg-gitt-opp/gi_opp/", to: "/har-jeg-gitt-opp/" },
  { from: "/hjem/cafe_slide/", to: "/" },
  { from: "/hjem/fjell_drom_sml/", to: "/" },
  { from: "/hjem/fjell_drom/", to: "/" },
  { from: "/hjem/min_egen_sjef_andreas/", to: "/" },
  { from: "/hjem/minegensjef_andreas_circle/", to: "/" },
  { from: "/hjem/minegensjef_andreas_circle2/", to: "/" },
  { from: "/hjem/vei_slide/", to: "/" },
  { from: "/hva-er-affiliate-markedsforing/affiliate_network_logo/", to: "/hva-er-affiliate-markedsforing/" },
  { from: "/hva-er-affiliate-markedsforing/affiliate_network_logos/", to: "/hva-er-affiliate-markedsforing/" },
  { from: "/hva-er-affiliate-markedsforing/hjemmekontor/", to: "/hva-er-affiliate-markedsforing/" },
  { from: "/hva-er-affiliate-markedsforing/hva_er_affiliate_markedsforing/", to: "/hva-er-affiliate-markedsforing/" },
  { from: "/hva-er-seo/hva_er_google_instant/", to: "/hva-er-seo/" },
  { from: "/hva-er-seo/hva_er_seo/", to: "/hva-er-seo/" },
  { from: "/hva-er-seo/hva_er_serp/", to: "/hva-er-seo/" },
  { from: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/amazon_bank_deposit/", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  { from: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/amazon_payoneer/", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  { from: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/payoneer_dnb/", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  { from: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/payoneer_minegensjef/", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  { from: "/hvordan-heve-sjekk-fra-utlandet-i-norge/hvordan_heve_sjekk_i_norge/", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  { from: "/hvordan-lage-nettside-na-til-dags/domenenavn/", to: "/hvordan-lage-nettside-na-til-dags/" },
  { from: "/hvordan-lage-nettside-na-til-dags/hvordan-lage-nettside/", to: "/hvordan-lage-nettside-na-til-dags/" },
  { from: "/hvordan-lage-nettside-na-til-dags/wordpress_kontrollpanel/", to: "/hvordan-lage-nettside-na-til-dags/" },
  { from: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/del_facebook/", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  { from: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/del_twitter/", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  { from: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/jobbe_cafe/", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  { from: "/merverdiavgift-og-affiliate-markedsforing/affiliate_merverdiavgift/", to: "/merverdiavgift-og-affiliate-markedsforing/" },
  { from: "/merverdiavgift-og-affiliate-markedsforing/merverdiavgift-og-affiliate-markedsforing/", to: "/merverdiavgift-og-affiliate-markedsforing/" },
  { from: "/min-forste-sjekk-pa-over-1000/amazon_sjekk/", to: "/min-forste-sjekk-pa-over-1000/" },
  { from: "/min-forste-sjekk-pa-over-1000/amazon_sjekk2/", to: "/min-forste-sjekk-pa-over-1000/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/add-missions/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/all-links/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/easy-to-reach/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/fatrank-score/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/health-open/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/health/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/how-to-fix-issue-forklaring/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/level-up-morningscore/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morningscore-linkscore/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morningscore-oppdrag/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morningscore-sokeordsanalyse/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morningscore-testet/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morningscore-value/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morninscore-anmeldelse/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morninscore-ebutikker/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morninscore-ranktracker/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morninscore-seo-helse-findings/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/morninscore-sokeord/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/multiple-h1-tags/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/onboarding-mission/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/space-suits/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/suggested-missions/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/unlocked-level-1/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/morningscore-anmeldelse-for-norsk-seo/video-thumbnail-what-is-morningscore/", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  { from: "/norske-affiliate-programmer/adrecord_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/adservice_affiliate_nettverk/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/adsninja_dashboard/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/adtraction_logo/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/adtraction_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/awin_screenshot-2/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/awin_screenshot-3/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/awin_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/daysicon_screendump/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/norske_affiliate_programmer_featured/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/norske_affiliate_programmer_featured2/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/partneradds_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/tradedoubler_logo/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/tradedoubler_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/tradetracker_logo/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/tradetracker_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/zanox_logo/", to: "/norske-affiliate-programmer/" },
  { from: "/norske-affiliate-programmer/zanox_screenshot/", to: "/norske-affiliate-programmer/" },
  { from: "/om-meg/blogs/", to: "/om/" },
  { from: "/om-meg/minegensjef_andreas_150/", to: "/om/" },
  { from: "/om-meg/minegensjef_andreas/", to: "/om/" },
  { from: "/regnskap-og-skatt-pa-affiliate-inntekter/skatt_regnskap_affiliate_inntekter/", to: "/regnskap-og-skatt-pa-affiliate-inntekter/" },
  { from: "/seriose-mater-a-tjene-penger-pa-nettet/seriose-mater-a-tjene-penger-pa-nett/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/slik-vurderer-google-kvalitet-9-ting-du-ma-vaere-klar-over/google_logo_update/", to: "/hva-er-seo/" },
  { from: "/slik-vurderer-google-kvalitet-9-ting-du-ma-vaere-klar-over/google_retningslinjer/", to: "/hva-er-seo/" },
  { from: "/slik-vurderer-google-kvalitet-9-ting-du-ma-vaere-klar-over/google_search_guidelines/", to: "/hva-er-seo/" },
  { from: "/suksess-motbakke-status-og-nye-mal-for-2017/amazon_inntekt/", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  { from: "/suksess-motbakke-status-og-nye-mal-for-2017/amazoncom_earnings/", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  { from: "/suksess-motbakke-status-og-nye-mal-for-2017/suksess_motbakke_status_featured/", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  { from: "/til-deg-som-sitter-hjemme-og-vil-tjene-penger-pa-nett/til-deg-som-sitter-hjemme/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/til-deg-som-sitter-hjemme-og-vil-tjene-penger-pa-nett/wealthy_affilliate_new_look/", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  { from: "/verdifulle-tips-fra-simon/simon_bak_andersen_gjestepost/", to: "/verdifulle-tips-fra-simon/" },
  { from: "/viktig-husk-pa-dette-nar-du-begynner-a-tjene-penger-pa-nett/viktig-a-huske-nar-man-tjener-penger-pa-affiliate/", to: "/viktig-husk-pa-dette-nar-du-begynner-a-tjene-penger-pa-nett/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/amazon_sjekk_250/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/anmeldelse_av_wealthy_affiliate/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/anmeldelse_wealthy_affiliate/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/hvordan_virker_wealthy_affiliate/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/hvordan_virker_wealthy_affiliate2/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/keyword_research_tool/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/netthotellet_wa_features/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/seo_wa_sertifiseringskurs/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/wa_live_chat/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/wa_score_ekte/", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  { from: "/wealthy-affiliate-black-friday-salg/wealthy_affiliate_blackfriday_offer/", to: "/wealthy-affiliate/" },
];

/**
 * Vedlegg uten publisert parent (ikke knyttet til noe innlegg, eller knyttet til et utkast): 410.
 * Vedlegg som bare har adressen `/?attachment_id=<id>`, dekkes av en egen regel i next.config.ts.
 */
export const goneAttachmentPaths: string[] = [
  "/adtraction_click_uten_strek/",
  "/cropped-logo2_divi-jpg/",
  "/favicon/",
  "/logo/",
  "/logo2/",
  "/logo2_amp/",
  "/logo2_divi/",
  "/logo3/",
  "/logo4/",
  "/logo5/",
  "/min_egen_sjef_andreas_twitter/",
  "/onecom_110kr_rabattkode/",
  "/onecom_discount_uten_strek/",
  "/proisp_anbefalt/",
  "/runner-in-green-forest-running-in-rain-sport-in-nature-trail-r/",
  "/strek_annonser2/",
  "/tjen_penger_online-2/",
  "/tjen_penger_online/",
  "/tjen_penger_pa_nett_uten_strek/",
  "/tradetracker_click_uten_strek/",
];
