/**
 * WordPress-ID-er fra WXR-eksporten 28.09.2026 → endelig mål. Brukes av `app/wp-id/route.ts`
 * for gamle spørringsadresser: `/?p=<id>`, `/?page_id=<id>` og `/?attachment_id=<id>`.
 *
 * Bare offentlige ID-er med et mål står her. Alle andre ID-er (utkast, vedlegg uten publisert
 * parent, og ID-er som ikke finnes) gir 410.
 *
 * 34 ID-er peker til en artikkel som er utsatt eller er 410-kandidat (`follows: true`).
 * De følger den artikkelens behandling. Får artikkelen 301, må målet her oppdateres så det ikke blir kjede.
 * Se docs/migration/wordpress-archives-and-media.md.
 */
export type WpIdTarget = { type: "post" | "page" | "attachment"; to: string; follows?: true };

export const wpIdTargets: Record<string, WpIdTarget> = {
  "7": { type: "page", to: "/om/" },
  "9": { type: "page", to: "/personvern/" },
  "11": { type: "page", to: "/kontakt/" },
  "93": { type: "page", to: "/ansvarsfraskrivelse/" },
  "100": { type: "attachment", to: "/om/" },
  "118": { type: "post", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  "119": { type: "attachment", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  "120": { type: "attachment", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  "129": { type: "attachment", to: "/introduksjon-drommen-om-a-bli-sin-egen-sjef/" },
  "134": { type: "page", to: "/" },
  "152": { type: "page", to: "/artikler/" },
  "156": { type: "attachment", to: "/" },
  "157": { type: "attachment", to: "/" },
  "158": { type: "attachment", to: "/" },
  "163": { type: "attachment", to: "/om/" },
  "165": { type: "attachment", to: "/" },
  "178": { type: "post", to: "/hva-er-affiliate-markedsforing/" },
  "180": { type: "attachment", to: "/hva-er-affiliate-markedsforing/" },
  "187": { type: "attachment", to: "/hva-er-affiliate-markedsforing/" },
  "194": { type: "attachment", to: "/hva-er-affiliate-markedsforing/" },
  "209": { type: "attachment", to: "/hva-er-affiliate-markedsforing/" },
  "216": { type: "attachment", to: "/" },
  "219": { type: "attachment", to: "/om/" },
  "221": { type: "attachment", to: "/" },
  "234": { type: "post", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "241": { type: "post", to: "/hvordan-lage-nettside-na-til-dags/" },
  "274": { type: "attachment", to: "/hvordan-lage-nettside-na-til-dags/" },
  "279": { type: "attachment", to: "/hvordan-lage-nettside-na-til-dags/" },
  "282": { type: "attachment", to: "/hvordan-lage-nettside-na-til-dags/" },
  "326": { type: "post", to: "/hva-er-seo/" },
  "337": { type: "attachment", to: "/hva-er-seo/" },
  "374": { type: "attachment", to: "/hva-er-seo/" },
  "377": { type: "attachment", to: "/hva-er-seo/" },
  "389": { type: "post", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "422": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "427": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "428": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "429": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "477": { type: "post", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "479": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "484": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "485": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "486": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "490": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "492": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "498": { type: "attachment", to: "/" },
  "504": { type: "attachment", to: "/amazon-julehandel-over-alle-stovelskaft/" },
  "535": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "539": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "543": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "544": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "546": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "553": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "564": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "572": { type: "post", to: "/min-forste-sjekk-pa-over-1000/" },
  "573": { type: "attachment", to: "/min-forste-sjekk-pa-over-1000/" },
  "593": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "604": { type: "post", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "631": { type: "attachment", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "635": { type: "attachment", to: "/min-forste-sjekk-pa-over-1000/" },
  "638": { type: "post", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "642": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "647": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "650": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "651": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "656": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "666": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "680": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "681": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "682": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "683": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "684": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "685": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "686": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "687": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "688": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "689": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "697": { type: "attachment", to: "/ifttt-er-et-nyttig-verktoy-for-a-automatisere-sma-oppgaver/", follows: true },
  "754": { type: "post", to: "/hva-er-seo/" },
  "974": { type: "attachment", to: "/hva-er-seo/" },
  "975": { type: "attachment", to: "/hva-er-seo/" },
  "977": { type: "attachment", to: "/hva-er-seo/" },
  "988": { type: "attachment", to: "/wealthy-affiliate-anmeldelse-en-gylden-mulighet/" },
  "998": { type: "post", to: "/anmeldelse_seo-that-works-2/", follows: true },
  "1023": { type: "post", to: "/de-beste-norske-seo-bloggene/" },
  "1028": { type: "attachment", to: "/anmeldelse_seo-that-works-2/", follows: true },
  "1029": { type: "attachment", to: "/anmeldelse_seo-that-works-2/", follows: true },
  "1031": { type: "attachment", to: "/anmeldelse_seo-that-works-2/", follows: true },
  "1063": { type: "post", to: "/tanker-rundt-inspirasjon/", follows: true },
  "1066": { type: "attachment", to: "/tanker-rundt-inspirasjon/", follows: true },
  "1067": { type: "attachment", to: "/tanker-rundt-inspirasjon/", follows: true },
  "1086": { type: "post", to: "/betalt-annonsering-med-google-adwords/", follows: true },
  "1090": { type: "attachment", to: "/betalt-annonsering-med-google-adwords/", follows: true },
  "1092": { type: "attachment", to: "/betalt-annonsering-med-google-adwords/", follows: true },
  "1106": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1111": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1114": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1115": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1119": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1120": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1121": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1122": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1125": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1126": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1128": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1130": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1131": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1137": { type: "post", to: "/norske-affiliate-programmer/" },
  "1144": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1145": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1146": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1147": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1150": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1151": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1152": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1153": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1160": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1169": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1178": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1211": { type: "post", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  "1215": { type: "attachment", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  "1219": { type: "attachment", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  "1226": { type: "attachment", to: "/suksess-motbakke-status-og-nye-mal-for-2017/" },
  "1245": { type: "post", to: "/verdifulle-tips-fra-simon/" },
  "1254": { type: "attachment", to: "/verdifulle-tips-fra-simon/" },
  "1365": { type: "post", to: "/har-jeg-gitt-opp/" },
  "1367": { type: "attachment", to: "/har-jeg-gitt-opp/" },
  "1378": { type: "post", to: "/wealthy-affiliate/" },
  "1379": { type: "attachment", to: "/wealthy-affiliate/" },
  "1395": { type: "post", to: "/gode-verktoy-for-sokeordsanalyse/" },
  "1445": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1446": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1447": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1448": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1463": { type: "post", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "1471": { type: "attachment", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "1472": { type: "attachment", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "1474": { type: "attachment", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "1476": { type: "attachment", to: "/hvordan-fa-amazon-inntekter-utbetalt-til-norsk-bankkonto/" },
  "1489": { type: "post", to: "/regnskap-og-skatt-pa-affiliate-inntekter/" },
  "1520": { type: "post", to: "/gratis-bilder/" },
  "1528": { type: "attachment", to: "/regnskap-og-skatt-pa-affiliate-inntekter/" },
  "1533": { type: "post", to: "/affiliate-markedsforing-i-norge-er-det-enklere/" },
  "1540": { type: "attachment", to: "/affiliate-markedsforing-i-norge-er-det-enklere/" },
  "1547": { type: "attachment", to: "/affiliate-markedsforing-i-norge-er-det-enklere/" },
  "1577": { type: "post", to: "/merverdiavgift-og-affiliate-markedsforing/" },
  "1588": { type: "attachment", to: "/merverdiavgift-og-affiliate-markedsforing/" },
  "1591": { type: "attachment", to: "/merverdiavgift-og-affiliate-markedsforing/" },
  "1623": { type: "attachment", to: "/gode-verktoy-for-sokeordsanalyse/" },
  "1624": { type: "attachment", to: "/gode-verktoy-for-sokeordsanalyse/" },
  "1625": { type: "attachment", to: "/gode-verktoy-for-sokeordsanalyse/" },
  "1626": { type: "attachment", to: "/gode-verktoy-for-sokeordsanalyse/" },
  "1642": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1654": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1690": { type: "post", to: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/" },
  "1691": { type: "attachment", to: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/" },
  "1692": { type: "attachment", to: "/er-amazon-sitt-affiliate-program-helt-ute-a-kjore/" },
  "1708": { type: "post", to: "/mine-erfaringer-med-affiliatenettverket-tradetracker/", follows: true },
  "1716": { type: "attachment", to: "/mine-erfaringer-med-affiliatenettverket-tradetracker/", follows: true },
  "1717": { type: "attachment", to: "/mine-erfaringer-med-affiliatenettverket-tradetracker/", follows: true },
  "1718": { type: "attachment", to: "/mine-erfaringer-med-affiliatenettverket-tradetracker/", follows: true },
  "1753": { type: "attachment", to: "/gratis-bilder/" },
  "1754": { type: "attachment", to: "/gratis-bilder/" },
  "1755": { type: "attachment", to: "/gratis-bilder/" },
  "1757": { type: "attachment", to: "/gratis-bilder/" },
  "1759": { type: "attachment", to: "/gratis-bilder/" },
  "1763": { type: "post", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "1772": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "1774": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "1801": { type: "attachment", to: "/norske-affiliate-programmer/" },
  "1849": { type: "attachment", to: "/de-beste-norske-seo-bloggene/" },
  "1851": { type: "post", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1856": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1857": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1859": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1861": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1862": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1863": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1864": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1866": { type: "post", to: "/chatgpt-og-affiliate-markedsforing/", follows: true },
  "1879": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1881": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1882": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1884": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1885": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1886": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1887": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1888": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1889": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1890": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1891": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1892": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1893": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1894": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1895": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1896": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1898": { type: "attachment", to: "/morningscore-anmeldelse-for-norsk-seo/" },
  "1902": { type: "attachment", to: "/gode-verktoy-for-sokeordsanalyse/" },
  "1905": { type: "attachment", to: "/chatgpt-og-affiliate-markedsforing/", follows: true },
  "1906": { type: "attachment", to: "/chatgpt-og-affiliate-markedsforing/", follows: true },
  "1913": { type: "post", to: "/viktig-husk-pa-dette-nar-du-begynner-a-tjene-penger-pa-nett/" },
  "1924": { type: "attachment", to: "/viktig-husk-pa-dette-nar-du-begynner-a-tjene-penger-pa-nett/" },
  "1963": { type: "post", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
  "1969": { type: "attachment", to: "/seriose-mater-a-tjene-penger-pa-nettet/" },
};
